[build]
  command = "npm run build" # или любая команда, которая используется для сборки вашего проекта
  functions = "functions"   # указываем путь к директории с функциями Netlify

[dev]
  functions = "functions"   # указываем путь к директории с функциями Netlify

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/proxy/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "14" # Версия Node.js для сборки проекта

[[plugins]]
  package = "@netlify/plugin-functions-install" # Плагин для установки зависимостей функций

